openapi: 3.0.3
info:
  title: Product Management API (WebFlux Functional)
  description: API para la gestión de productos, implementada con Spring WebFlux Functional Endpoints.
  version: v1.0.0
servers:
  - url: http://localhost:8080/
    description: Servidor local
tags:
  - name: Products
    description: Operaciones CRUD para la entidad Producto.
  - name: Stock Management
    description: Endpoints para modificar el stock de productos.

paths:
  /products:
    get:
      tags:
        - Products
      summary: Obtener todos los productos
      operationId: getAllProducts
      responses:
        '200':
          description: Lista de productos obtenida con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessListResponse'
        '404':
          $ref: '#/components/responses/NotFound'
    post:
      tags:
        - Products
      summary: Crear un nuevo producto
      operationId: createProduct
      requestBody:
        description: Producto a crear. El campo 'id' será ignorado o generado por el sistema.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreateRequest'
      responses:
        '201':
          description: Producto creado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessObjectResponse'
        '400':
          $ref: '#/components/responses/BadRequest'

  /products/{id}:
    get:
      tags:
        - Products
      summary: Obtener producto por ID
      operationId: getProductById
      parameters:
        - name: id
          in: path
          description: ID del producto a buscar
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessObjectResponse'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      tags:
        - Products
      summary: Actualizar un producto existente
      operationId: updateProduct
      parameters:
        - name: id
          in: path
          description: ID del producto a actualizar
          required: true
          schema:
            type: integer
      requestBody:
        description: Nuevos detalles del producto.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpdateRequest'
      responses:
        '200':
          description: Producto actualizado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessObjectResponse'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags:
        - Products
      summary: Eliminar un producto por ID
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          description: ID del producto a eliminar
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Producto eliminado con éxito (Sin contenido)
        '404':
          $ref: '#/components/responses/NotFound'

  /products/increasestock/{id}:
    put:
      tags:
        - Stock Management
      summary: Incrementar el stock del producto
      description: Incrementa el stock del producto identificado por ID.
      operationId: increaseStock
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Cantidad a incrementar (opcional, por defecto 1)
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  example: 1
      responses:
        '200':
          description: Stock incrementado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessObjectResponse'
        '404':
          $ref: '#/components/responses/NotFound'

  /products/decreasestock/{id}:
    put:
      tags:
        - Stock Management
      summary: Decrementar el stock del producto
      description: Decrementa el stock del producto identificado por ID.
      operationId: decreaseStock
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Cantidad a decrementar (opcional, por defecto 1)
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  example: 1
      responses:
        '200':
          description: Stock decrementado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessObjectResponse'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 101
        name:
          type: string
          example: Laptop Ultra
        description:
          type: string
          example: Portátil de alto rendimiento con 32GB de RAM
        price:
          type: number
          format: float
          example: 1250.99
        stock:
          type: integer
          example: 45
      required: [name, price, stock]

    ProductCreateRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        stock:
          type: integer
      required: [name, price, stock]

    ProductUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/ProductCreateRequest'

    SuccessBase:
      type: object
      properties:
        success:
          type: boolean
          default: true
        message:
          type: string
          example: Operación exitosa

    SuccessObjectResponse:
      allOf:
        - $ref: '#/components/schemas/SuccessBase'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/Product'

    SuccessListResponse:
      allOf:
        - $ref: '#/components/schemas/SuccessBase'
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/Product'

    ErrorDetail:
      type: object
      properties:
        code:
          type: string
          example: E400_INVALID_INPUT
        message:
          type: string
          example: Campo requerido faltante
        field:
          type: string
          example: name

    ErrorModel:
      allOf:
        - $ref: '#/components/schemas/SuccessBase'
        - type: object
          properties:
            success:
              type: boolean
              default: false
            errors:
              type: array
              items:
                $ref: '#/components/schemas/ErrorDetail'
      required: [success, errors]

  responses:
    BadRequest:
      description: Solicitud inválida
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'

    NotFound:
      description: Recurso no encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
